// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "xUnit1044:Avoid using TheoryData type arguments that are not serializable", Justification = "We use non-serializable args to simplify the test", Scope = "member", Target = "~M:Scand.StormPetrel.Generator.Analyzer.Test.AppSettingsFileReferenceAnalyzerTest.MainTest(System.String,System.ValueTuple{System.String,Microsoft.CodeAnalysis.Text.SourceText}[],System.ValueTuple{System.Collections.Generic.Dictionary{System.String,System.String},System.Func{System.String,System.Collections.Generic.IEnumerable{System.String}},System.Func{System.Int64}},System.Nullable{Microsoft.CodeAnalysis.Testing.DiagnosticResult},System.Collections.Generic.Dictionary{System.String,System.String})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "xUnit1045:Avoid using TheoryData type arguments that might not be serializable", Justification = "We use non-serializable args to simplify the test", Scope = "member", Target = "~M:Scand.StormPetrel.Generator.Analyzer.Test.AppSettingsFileReferenceAnalyzerTest.MainTest(System.String,System.ValueTuple{System.String,Microsoft.CodeAnalysis.Text.SourceText}[],System.ValueTuple{System.Collections.Generic.Dictionary{System.String,System.String},System.Func{System.String,System.Collections.Generic.IEnumerable{System.String}},System.Func{System.Int64}},System.Nullable{Microsoft.CodeAnalysis.Testing.DiagnosticResult},System.Collections.Generic.Dictionary{System.String,System.String})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "Intentionally test the use case", Scope = "member", Target = "~M:Scand.StormPetrel.Generator.Analyzer.Test.IsTestDataSourceMethodSuitableForBaselineUpdateAnalyzerTest.MSTestNoReportDiagnostic(System.ValueTuple{System.String,System.String}[])~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "Intentionally test the use case", Scope = "member", Target = "~M:Scand.StormPetrel.Generator.Analyzer.Test.IsTestDataSourceMethodSuitableForBaselineUpdateAnalyzerTest.NUnitNoReportDiagnostic(System.ValueTuple{System.String,System.String}[])~System.Threading.Tasks.Task")]
