// <auto-generated />
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable enable
#endif
using FluentAssertions;
using Xunit.Sdk;

namespace Test.Integration.XUnit
{
    [global::System.CodeDom.Compiler.GeneratedCode("Scand.StormPetrel.Generator", "2.7.0")]
    public class UnitTest1StormPetrel
    {
        [Fact]
        public void Test1StormPetrel()
        {
            //Arrange
            int expected = 1;
            //Act
            expected = 2;
            var actual = TestedClass.TestedMethod1();
            expected = 3;
            var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
            {
                FilePath = "C:\\temp\\temp.cs",
                ClassName = "UnitTest1",
                MethodName = "Test1",
                VariablePairCurrentIndex = 0,
                VariablePairsCount = 1,
                Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
                {
                }
            };
            var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
            {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ActualVariablePath = new[]
                {
                    "Test.Integration.XUnit",
                    "UnitTest1",
                    "Test1",
                    "actual"
                },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Expected = expected
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ExpectedVariablePath = new[]
                {
                    "Test.Integration.XUnit",
                    "UnitTest1",
                    "Test1",
                    "expected[1]"
                },
                ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InitializerContext()
                {
                    Kind = Scand.StormPetrel.Generator.Abstraction.ExtraContext.InitializerContextKind.VariableAssignment
                },
                MethodSharedContext = stormPetrelSharedContext
            };
            ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
            //Assert
            actual.Should().Be(expected);
        }
    }
}