// <auto-generated />
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable enable
#endif
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Scand.StormPetrel.Generator.Test.Resource
{
    [global::System.CodeDom.Compiler.GeneratedCode("Scand.StormPetrel.Generator", "2.7.0")]
    internal class ClassDataTestsStormPetrel
    {
        [Theory]
        [ClassData(typeof(SomeClass))]
        public void TestStormPetrel(int x, int y, int expected)
        {
            var actual = Calculator.Add(x, y);
            var stormPetrelSharedContext = new global::Scand.StormPetrel.Generator.Abstraction.MethodContext()
            {
                FilePath = "C:\\temp\\temp.cs",
                ClassName = "ClassDataTests",
                MethodName = "Test",
                VariablePairCurrentIndex = 0,
                VariablePairsCount = 1,
                Parameters = new[]
                {
                    new global::Scand.StormPetrel.Generator.Abstraction.ParameterInfo()
                    {
                        Name = "x",
                        Value = x,
                        TypeToken = "int"
                    },
                    new global::Scand.StormPetrel.Generator.Abstraction.ParameterInfo()
                    {
                        Name = "y",
                        Value = y,
                        TypeToken = "int"
                    },
                    new global::Scand.StormPetrel.Generator.Abstraction.ParameterInfo()
                    {
                        Name = "expected",
                        Value = expected,
                        TypeToken = "int"
                    }
                }
            };
            var stormPetrelTestCaseSourceRowIndex = -1;
            var stormPetrelIsTestCaseSourceRowExist = false;
            var stormPetrelRows = global::Scand.StormPetrel.Rewriter.DataSourceHelper.ConvertToStormPetrelRows(new SomeClass());
            foreach (var stormPetrelRow in stormPetrelRows)
            {
                stormPetrelTestCaseSourceRowIndex++;
                if ((stormPetrelRow.Length > 0 && (x == (int)stormPetrelRow[0] || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(x, stormPetrelRow[0]) || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(x, stormPetrelRow[0])) || stormPetrelRow.Length <= 0 && x == default(int)) && (stormPetrelRow.Length > 1 && (y == (int)stormPetrelRow[1] || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(y, stormPetrelRow[1]) || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(y, stormPetrelRow[1])) || stormPetrelRow.Length <= 1 && y == default(int)))
                {
                    stormPetrelIsTestCaseSourceRowExist = true;
                    break;
                }
            }

            if (!stormPetrelIsTestCaseSourceRowExist)
            {
                var stormPetrelNoEqualArgNames = new global::System.Collections.Generic.List<string>()
                {
                    "x",
                    "y"
                };
                foreach (var stormPetrelRow in stormPetrelRows)
                {
                    if (stormPetrelRow.Length > 0 && (x == (int)stormPetrelRow[0] || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(x, stormPetrelRow[0]) || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(x, stormPetrelRow[0])) || stormPetrelRow.Length <= 0 && x == default(int))
                    {
                        stormPetrelNoEqualArgNames.Remove("x");
                    }

                    if (stormPetrelRow.Length > 1 && (y == (int)stormPetrelRow[1] || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(y, stormPetrelRow[1]) || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(y, stormPetrelRow[1])) || stormPetrelRow.Length <= 1 && y == default(int))
                    {
                        stormPetrelNoEqualArgNames.Remove("y");
                    }
                }

                throw new global::System.InvalidOperationException("Cannot detect appropriate test case source row to rewrite. Test method argument(s) giving the failure: '" + string.Join("', '", stormPetrelNoEqualArgNames) + "'. To understand the failure root cause you can debug the conditions above returning unexpected value for the argument(s).");
            }

            var stormPetrelContext = new global::Scand.StormPetrel.Generator.Abstraction.GenerationContext()
            {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ActualVariablePath = new[]
                {
                    "Scand.StormPetrel.Generator.Test.Resource",
                    "ClassDataTests",
                    "Test",
                    "actual"
                },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Expected = expected
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ExpectedVariablePath = new[]
                {
                    "Scand.StormPetrel.Generator.Test.Resource",
                    "ClassDataTests",
                    "Test"
                },
                ExtraContext = new global::Scand.StormPetrel.Generator.Abstraction.ExtraContext.TestCaseSourceContext()
                {
                    ColumnIndex = 2,
                    RowIndex = stormPetrelTestCaseSourceRowIndex,
                    Path = Scand.StormPetrel.Rewriter.DataSourceHelper.GetEnumerableStaticMemberPath(typeof(SomeClass))
                },
                MethodSharedContext = stormPetrelSharedContext
            };
            ((global::Scand.StormPetrel.Generator.Abstraction.IGenerator)new global::Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
            Assert.Equal(expected, actual);
        }

        [Theory]
        [ClassData(typeof(SomeClass))]
        public void MultipleVarsTestStormPetrel(int x, int y, int expected, string expectedString)
        {
            var actual = Calculator.Add(x, y);
            var stormPetrelSharedContext = new global::Scand.StormPetrel.Generator.Abstraction.MethodContext()
            {
                FilePath = "C:\\temp\\temp.cs",
                ClassName = "ClassDataTests",
                MethodName = "MultipleVarsTest",
                VariablePairCurrentIndex = 0,
                VariablePairsCount = 2,
                Parameters = new[]
                {
                    new global::Scand.StormPetrel.Generator.Abstraction.ParameterInfo()
                    {
                        Name = "x",
                        Value = x,
                        TypeToken = "int"
                    },
                    new global::Scand.StormPetrel.Generator.Abstraction.ParameterInfo()
                    {
                        Name = "y",
                        Value = y,
                        TypeToken = "int"
                    },
                    new global::Scand.StormPetrel.Generator.Abstraction.ParameterInfo()
                    {
                        Name = "expected",
                        Value = expected,
                        TypeToken = "int"
                    },
                    new global::Scand.StormPetrel.Generator.Abstraction.ParameterInfo()
                    {
                        Name = "expectedString",
                        Value = expectedString,
                        TypeToken = "string"
                    }
                }
            };
            var stormPetrelTestCaseSourceRowIndex = -1;
            var stormPetrelIsTestCaseSourceRowExist = false;
            var stormPetrelRows = global::Scand.StormPetrel.Rewriter.DataSourceHelper.ConvertToStormPetrelRows(new SomeClass());
            foreach (var stormPetrelRow in stormPetrelRows)
            {
                stormPetrelTestCaseSourceRowIndex++;
                if ((stormPetrelRow.Length > 0 && (x == (int)stormPetrelRow[0] || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(x, stormPetrelRow[0]) || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(x, stormPetrelRow[0])) || stormPetrelRow.Length <= 0 && x == default(int)) && (stormPetrelRow.Length > 1 && (y == (int)stormPetrelRow[1] || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(y, stormPetrelRow[1]) || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(y, stormPetrelRow[1])) || stormPetrelRow.Length <= 1 && y == default(int)))
                {
                    stormPetrelIsTestCaseSourceRowExist = true;
                    break;
                }
            }

            if (!stormPetrelIsTestCaseSourceRowExist)
            {
                var stormPetrelNoEqualArgNames = new global::System.Collections.Generic.List<string>()
                {
                    "x",
                    "y"
                };
                foreach (var stormPetrelRow in stormPetrelRows)
                {
                    if (stormPetrelRow.Length > 0 && (x == (int)stormPetrelRow[0] || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(x, stormPetrelRow[0]) || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(x, stormPetrelRow[0])) || stormPetrelRow.Length <= 0 && x == default(int))
                    {
                        stormPetrelNoEqualArgNames.Remove("x");
                    }

                    if (stormPetrelRow.Length > 1 && (y == (int)stormPetrelRow[1] || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(y, stormPetrelRow[1]) || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(y, stormPetrelRow[1])) || stormPetrelRow.Length <= 1 && y == default(int))
                    {
                        stormPetrelNoEqualArgNames.Remove("y");
                    }
                }

                throw new global::System.InvalidOperationException("Cannot detect appropriate test case source row to rewrite. Test method argument(s) giving the failure: '" + string.Join("', '", stormPetrelNoEqualArgNames) + "'. To understand the failure root cause you can debug the conditions above returning unexpected value for the argument(s).");
            }

            var stormPetrelContext = new global::Scand.StormPetrel.Generator.Abstraction.GenerationContext()
            {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ActualVariablePath = new[]
                {
                    "Scand.StormPetrel.Generator.Test.Resource",
                    "ClassDataTests",
                    "MultipleVarsTest",
                    "actual"
                },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Expected = expected
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ExpectedVariablePath = new[]
                {
                    "Scand.StormPetrel.Generator.Test.Resource",
                    "ClassDataTests",
                    "MultipleVarsTest"
                },
                ExtraContext = new global::Scand.StormPetrel.Generator.Abstraction.ExtraContext.TestCaseSourceContext()
                {
                    ColumnIndex = 2,
                    RowIndex = stormPetrelTestCaseSourceRowIndex,
                    Path = Scand.StormPetrel.Rewriter.DataSourceHelper.GetEnumerableStaticMemberPath(typeof(SomeClass))
                },
                MethodSharedContext = stormPetrelSharedContext
            };
            ((global::Scand.StormPetrel.Generator.Abstraction.IGenerator)new global::Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
            var actualString = actual.ToString();
            stormPetrelSharedContext.VariablePairCurrentIndex++;
            var stormPetrelTestCaseSourceRowIndex1 = -1;
            var stormPetrelIsTestCaseSourceRowExist1 = false;
            var stormPetrelRows1 = global::Scand.StormPetrel.Rewriter.DataSourceHelper.ConvertToStormPetrelRows(new SomeClass());
            foreach (var stormPetrelRow in stormPetrelRows1)
            {
                stormPetrelTestCaseSourceRowIndex1++;
                if ((stormPetrelRow.Length > 0 && (x == (int)stormPetrelRow[0] || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(x, stormPetrelRow[0]) || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(x, stormPetrelRow[0])) || stormPetrelRow.Length <= 0 && x == default(int)) && (stormPetrelRow.Length > 1 && (y == (int)stormPetrelRow[1] || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(y, stormPetrelRow[1]) || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(y, stormPetrelRow[1])) || stormPetrelRow.Length <= 1 && y == default(int)))
                {
                    stormPetrelIsTestCaseSourceRowExist1 = true;
                    break;
                }
            }

            if (!stormPetrelIsTestCaseSourceRowExist1)
            {
                var stormPetrelNoEqualArgNames1 = new global::System.Collections.Generic.List<string>()
                {
                    "x",
                    "y"
                };
                foreach (var stormPetrelRow in stormPetrelRows1)
                {
                    if (stormPetrelRow.Length > 0 && (x == (int)stormPetrelRow[0] || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(x, stormPetrelRow[0]) || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(x, stormPetrelRow[0])) || stormPetrelRow.Length <= 0 && x == default(int))
                    {
                        stormPetrelNoEqualArgNames1.Remove("x");
                    }

                    if (stormPetrelRow.Length > 1 && (y == (int)stormPetrelRow[1] || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(y, stormPetrelRow[1]) || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(y, stormPetrelRow[1])) || stormPetrelRow.Length <= 1 && y == default(int))
                    {
                        stormPetrelNoEqualArgNames1.Remove("y");
                    }
                }

                throw new global::System.InvalidOperationException("Cannot detect appropriate test case source row to rewrite. Test method argument(s) giving the failure: '" + string.Join("', '", stormPetrelNoEqualArgNames1) + "'. To understand the failure root cause you can debug the conditions above returning unexpected value for the argument(s).");
            }

            var stormPetrelContext1 = new global::Scand.StormPetrel.Generator.Abstraction.GenerationContext()
            {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Actual = actualString
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ActualVariablePath = new[]
                {
                    "Scand.StormPetrel.Generator.Test.Resource",
                    "ClassDataTests",
                    "MultipleVarsTest",
                    "actualString"
                },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Expected = expectedString
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ExpectedVariablePath = new[]
                {
                    "Scand.StormPetrel.Generator.Test.Resource",
                    "ClassDataTests",
                    "MultipleVarsTest"
                },
                ExtraContext = new global::Scand.StormPetrel.Generator.Abstraction.ExtraContext.TestCaseSourceContext()
                {
                    ColumnIndex = 3,
                    RowIndex = stormPetrelTestCaseSourceRowIndex1,
                    Path = Scand.StormPetrel.Rewriter.DataSourceHelper.GetEnumerableStaticMemberPath(typeof(SomeClass))
                },
                MethodSharedContext = stormPetrelSharedContext
            };
            ((global::Scand.StormPetrel.Generator.Abstraction.IGenerator)new global::Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext1);
            Assert.Equal(expected, actual);
            Assert.Equal(expectedString, actualString);
        }

        [Theory]
        [ClassData(typeof(SomeClass))]
        public void TypeofWhitespacesTestStormPetrel(int x, int y, int expected)
        {
            var actual = Calculator.Add(x, y);
            var stormPetrelSharedContext = new global::Scand.StormPetrel.Generator.Abstraction.MethodContext()
            {
                FilePath = "C:\\temp\\temp.cs",
                ClassName = "ClassDataTests",
                MethodName = "TypeofWhitespacesTest",
                VariablePairCurrentIndex = 0,
                VariablePairsCount = 1,
                Parameters = new[]
                {
                    new global::Scand.StormPetrel.Generator.Abstraction.ParameterInfo()
                    {
                        Name = "x",
                        Value = x,
                        TypeToken = "int"
                    },
                    new global::Scand.StormPetrel.Generator.Abstraction.ParameterInfo()
                    {
                        Name = "y",
                        Value = y,
                        TypeToken = "int"
                    },
                    new global::Scand.StormPetrel.Generator.Abstraction.ParameterInfo()
                    {
                        Name = "expected",
                        Value = expected,
                        TypeToken = "int"
                    }
                }
            };
            var stormPetrelTestCaseSourceRowIndex = -1;
            var stormPetrelIsTestCaseSourceRowExist = false;
            var stormPetrelRows = global::Scand.StormPetrel.Rewriter.DataSourceHelper.ConvertToStormPetrelRows(new SomeClass());
            foreach (var stormPetrelRow in stormPetrelRows)
            {
                stormPetrelTestCaseSourceRowIndex++;
                if ((stormPetrelRow.Length > 0 && (x == (int)stormPetrelRow[0] || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(x, stormPetrelRow[0]) || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(x, stormPetrelRow[0])) || stormPetrelRow.Length <= 0 && x == default(int)) && (stormPetrelRow.Length > 1 && (y == (int)stormPetrelRow[1] || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(y, stormPetrelRow[1]) || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(y, stormPetrelRow[1])) || stormPetrelRow.Length <= 1 && y == default(int)))
                {
                    stormPetrelIsTestCaseSourceRowExist = true;
                    break;
                }
            }

            if (!stormPetrelIsTestCaseSourceRowExist)
            {
                var stormPetrelNoEqualArgNames = new global::System.Collections.Generic.List<string>()
                {
                    "x",
                    "y"
                };
                foreach (var stormPetrelRow in stormPetrelRows)
                {
                    if (stormPetrelRow.Length > 0 && (x == (int)stormPetrelRow[0] || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(x, stormPetrelRow[0]) || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(x, stormPetrelRow[0])) || stormPetrelRow.Length <= 0 && x == default(int))
                    {
                        stormPetrelNoEqualArgNames.Remove("x");
                    }

                    if (stormPetrelRow.Length > 1 && (y == (int)stormPetrelRow[1] || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(y, stormPetrelRow[1]) || global::Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(y, stormPetrelRow[1])) || stormPetrelRow.Length <= 1 && y == default(int))
                    {
                        stormPetrelNoEqualArgNames.Remove("y");
                    }
                }

                throw new global::System.InvalidOperationException("Cannot detect appropriate test case source row to rewrite. Test method argument(s) giving the failure: '" + string.Join("', '", stormPetrelNoEqualArgNames) + "'. To understand the failure root cause you can debug the conditions above returning unexpected value for the argument(s).");
            }

            var stormPetrelContext = new global::Scand.StormPetrel.Generator.Abstraction.GenerationContext()
            {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ActualVariablePath = new[]
                {
                    "Scand.StormPetrel.Generator.Test.Resource",
                    "ClassDataTests",
                    "TypeofWhitespacesTest",
                    "actual"
                },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Expected = expected
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ExpectedVariablePath = new[]
                {
                    "Scand.StormPetrel.Generator.Test.Resource",
                    "ClassDataTests",
                    "TypeofWhitespacesTest"
                },
                ExtraContext = new global::Scand.StormPetrel.Generator.Abstraction.ExtraContext.TestCaseSourceContext()
                {
                    ColumnIndex = 2,
                    RowIndex = stormPetrelTestCaseSourceRowIndex,
                    Path = Scand.StormPetrel.Rewriter.DataSourceHelper.GetEnumerableStaticMemberPath(typeof(SomeClass))
                },
                MethodSharedContext = stormPetrelSharedContext
            };
            ((global::Scand.StormPetrel.Generator.Abstraction.IGenerator)new global::Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
            Assert.Equal(expected, actual);
        }
    }
}