// <auto-generated />
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable enable
#endif
using FluentAssertions;
using Xunit.Sdk;

namespace Test.Integration.XUnit
{
    [global::System.CodeDom.Compiler.GeneratedCode("Scand.StormPetrel.Generator", "2.7.0")]
    public class IgnoreInvocationExpressionTestStormPetrel
    {
        [Fact]
        public void ShouldIgnoreInvocationExpressionTestStormPetrel()
        {
            //Arrange
            int expected = InvocationExpressionToBeIgnored();
            //Act
            var actual = TestedClass.TestedMethod1();
            var stormPetrelSharedContext = new global::Scand.StormPetrel.Generator.Abstraction.MethodContext()
            {
                FilePath = "C:\\temp\\temp.cs",
                ClassName = "IgnoreInvocationExpressionTest",
                MethodName = "ShouldIgnoreInvocationExpressionTest",
                VariablePairCurrentIndex = 0,
                VariablePairsCount = 1
            };
            var stormPetrelContext = new global::Scand.StormPetrel.Generator.Abstraction.GenerationContext()
            {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ActualVariablePath = new[]
                {
                    "Test.Integration.XUnit",
                    "IgnoreInvocationExpressionTest",
                    "ShouldIgnoreInvocationExpressionTest",
                    "actual"
                },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Expected = expected
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ExpectedVariablePath = new[]
                {
                    "Test.Integration.XUnit",
                    "IgnoreInvocationExpressionTest",
                    "ShouldIgnoreInvocationExpressionTest",
                    "expected"
                },
                ExtraContext = new global::Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
                {
                    Path = new[]
                    {
                        "Test.Integration.XUnit",
                        "IgnoreInvocationExpressionTest",
                        "InvocationExpressionToBeIgnored[*]"
                    },
                    MethodInfo = new global::Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodNodeInfo()
                    {
                        MethodArgsCount = 0
                    }
                },
                MethodSharedContext = stormPetrelSharedContext
            };
            ((global::Scand.StormPetrel.Generator.Abstraction.IGenerator)new global::Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
            //Assert
            actual.Should().Be(expected);
        }

        [Fact]
        public void ShouldNotIgnoreInvocationExpressionDueToCaseSensitivityTestStormPetrel()
        {
            //Arrange
            int expected = InvocationExpressiontobeignored(); //should not be ignored
            //Act
            var actual = TestedClass.TestedMethod1();
            var stormPetrelSharedContext = new global::Scand.StormPetrel.Generator.Abstraction.MethodContext()
            {
                FilePath = "C:\\temp\\temp.cs",
                ClassName = "IgnoreInvocationExpressionTest",
                MethodName = "ShouldNotIgnoreInvocationExpressionDueToCaseSensitivityTest",
                VariablePairCurrentIndex = 0,
                VariablePairsCount = 1
            };
            var stormPetrelMethodNode = InvocationExpressiontobeignoredStormPetrel();
            var stormPetrelContext = new global::Scand.StormPetrel.Generator.Abstraction.GenerationContext()
            {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ActualVariablePath = new[]
                {
                    "Test.Integration.XUnit",
                    "IgnoreInvocationExpressionTest",
                    "ShouldNotIgnoreInvocationExpressionDueToCaseSensitivityTest",
                    "actual"
                },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Expected = expected
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ExpectedVariablePath = new[]
                {
                    "Test.Integration.XUnit",
                    "IgnoreInvocationExpressionTest",
                    "ShouldNotIgnoreInvocationExpressionDueToCaseSensitivityTest",
                    "expected"
                },
                ExtraContext = new global::Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
                {
                    Path = new[]
                    {
                        "Test.Integration.XUnit",
                        "IgnoreInvocationExpressionTest",
                        "InvocationExpressiontobeignored[*]"
                    },
                    MethodInfo = new global::Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodNodeInfo()
                    {
                        NodeKind = stormPetrelMethodNode.NodeKind,
                        NodeIndex = stormPetrelMethodNode.NodeIndex,
                        MethodArgsCount = 0
                    }
                },
                MethodSharedContext = stormPetrelSharedContext
            };
            ((global::Scand.StormPetrel.Generator.Abstraction.IGenerator)new global::Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
            //Assert
            actual.Should().Be(expected);
        }
    }
}