// <auto-generated />
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable enable
#endif
using FluentAssertions;
using Xunit.Sdk;

namespace Test.Integration.XUnit
{
    [global::System.CodeDom.Compiler.GeneratedCode("Scand.StormPetrel.Generator", "2.7.0")]
    public class AssertionNoExpectedVarTestStormPetrel
    {
        [Fact]
        public void ShouldDetectExpectedArgumentTestStormPetrel()
        {
            //Act
            var actual = TestedClass.TestedMethod1();
            var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
            {
                FilePath = "C:\\temp\\temp.cs",
                ClassName = "AssertionNoExpectedVarTest",
                MethodName = "ShouldDetectExpectedArgumentTest",
                VariablePairCurrentIndex = 0,
                VariablePairsCount = 1,
                Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
                {
                }
            };
            var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
            {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ActualVariablePath = new[]
                {
                    "Test.Integration.XUnit",
                    "AssertionNoExpectedVarTest",
                    "ShouldDetectExpectedArgumentTest"
                },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Expected = 1
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSourceContext()
                {
                    Path = new[]
                    {
                        "experimental-method-body-statement-index:1",
                        "Test.Integration.XUnit",
                        "AssertionNoExpectedVarTest",
                        "ShouldDetectExpectedArgumentTest"
                    },
                    MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSourceMethodInfo()
                    {
                        NodeKind = 8638,
                        NodeIndex = 0,
                        ArgsCount = 0
                    }
                },
                MethodSharedContext = stormPetrelSharedContext
            };
            ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
            //Assert
            actual.Should().Be(1);
        }

        [Fact]
        public void ShouldDetectExpectedArgumentWhenMultipleArgsTestStormPetrel()
        {
            //Act
            var actual = TestedClass.TestedMethod1();
            var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
            {
                FilePath = "C:\\temp\\temp.cs",
                ClassName = "AssertionNoExpectedVarTest",
                MethodName = "ShouldDetectExpectedArgumentWhenMultipleArgsTest",
                VariablePairCurrentIndex = 0,
                VariablePairsCount = 1,
                Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
                {
                }
            };
            var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
            {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ActualVariablePath = new[]
                {
                    "Test.Integration.XUnit",
                    "AssertionNoExpectedVarTest",
                    "ShouldDetectExpectedArgumentWhenMultipleArgsTest"
                },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Expected = 123
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSourceContext()
                {
                    Path = new[]
                    {
                        "experimental-method-body-statement-index:1",
                        "Test.Integration.XUnit",
                        "AssertionNoExpectedVarTest",
                        "ShouldDetectExpectedArgumentWhenMultipleArgsTest"
                    },
                    MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSourceMethodInfo()
                    {
                        NodeKind = 8638,
                        NodeIndex = 0,
                        ArgsCount = 0
                    }
                },
                MethodSharedContext = stormPetrelSharedContext
            };
            ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
            //Assert
            actual.Should().Be(123, "some explanation");
        }

        [Fact]
        public void ShouldDetectExpectedArgumentWhenMultipleNamedArgsTestStormPetrel()
        {
            //Act
            var actual = TestedClass.TestedMethod1();
            var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
            {
                FilePath = "C:\\temp\\temp.cs",
                ClassName = "AssertionNoExpectedVarTest",
                MethodName = "ShouldDetectExpectedArgumentWhenMultipleNamedArgsTest",
                VariablePairCurrentIndex = 0,
                VariablePairsCount = 1,
                Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
                {
                }
            };
            var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
            {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ActualVariablePath = new[]
                {
                    "Test.Integration.XUnit",
                    "AssertionNoExpectedVarTest",
                    "ShouldDetectExpectedArgumentWhenMultipleNamedArgsTest"
                },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Expected = 123
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSourceContext()
                {
                    Path = new[]
                    {
                        "experimental-method-body-statement-index:1",
                        "Test.Integration.XUnit",
                        "AssertionNoExpectedVarTest",
                        "ShouldDetectExpectedArgumentWhenMultipleNamedArgsTest"
                    },
                    MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSourceMethodInfo()
                    {
                        NodeKind = 8638,
                        NodeIndex = 1,
                        ArgsCount = 0
                    }
                },
                MethodSharedContext = stormPetrelSharedContext
            };
            ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
            //Assert
            actual.Should().Be(because: "some explanation", expected: 123);
        }

        [Fact]
        public void ShouldDetectExpectedArgumentWhenObjectCreationExpressionTestStormPetrel()
        {
            //Act
            var actual = TestedClass.TestedMethod1();
            var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
            {
                FilePath = "C:\\temp\\temp.cs",
                ClassName = "AssertionNoExpectedVarTest",
                MethodName = "ShouldDetectExpectedArgumentWhenObjectCreationExpressionTest",
                VariablePairCurrentIndex = 0,
                VariablePairsCount = 1,
                Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
                {
                }
            };
            var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
            {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ActualVariablePath = new[]
                {
                    "Test.Integration.XUnit",
                    "AssertionNoExpectedVarTest",
                    "ShouldDetectExpectedArgumentWhenObjectCreationExpressionTest"
                },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Expected = new FooExpected
                {
                    BlaProperty = "123"
                }
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSourceContext()
                {
                    Path = new[]
                    {
                        "experimental-method-body-statement-index:1",
                        "Test.Integration.XUnit",
                        "AssertionNoExpectedVarTest",
                        "ShouldDetectExpectedArgumentWhenObjectCreationExpressionTest"
                    },
                    MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSourceMethodInfo()
                    {
                        NodeKind = 8638,
                        NodeIndex = 0,
                        ArgsCount = 0
                    }
                },
                MethodSharedContext = stormPetrelSharedContext
            };
            ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
            //Assert
            actual.Should().BeEquivalentTo(new FooExpected { BlaProperty = "123" });
        }

        [Fact]
        public void ShouldDetectExpectedArgumentAndActualWithPropertyTestStormPetrel()
        {
            //Act
            var actual = TestedClass.TestedMethod1();
            var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
            {
                FilePath = "C:\\temp\\temp.cs",
                ClassName = "AssertionNoExpectedVarTest",
                MethodName = "ShouldDetectExpectedArgumentAndActualWithPropertyTest",
                VariablePairCurrentIndex = 0,
                VariablePairsCount = 1,
                Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
                {
                }
            };
            var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
            {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Actual = actual.FooProperty
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ActualVariablePath = new[]
                {
                    "Test.Integration.XUnit",
                    "AssertionNoExpectedVarTest",
                    "ShouldDetectExpectedArgumentAndActualWithPropertyTest"
                },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Expected = 1
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSourceContext()
                {
                    Path = new[]
                    {
                        "experimental-method-body-statement-index:1",
                        "Test.Integration.XUnit",
                        "AssertionNoExpectedVarTest",
                        "ShouldDetectExpectedArgumentAndActualWithPropertyTest"
                    },
                    MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSourceMethodInfo()
                    {
                        NodeKind = 8638,
                        NodeIndex = 0,
                        ArgsCount = 0
                    }
                },
                MethodSharedContext = stormPetrelSharedContext
            };
            ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
            //Assert
            actual.FooProperty.Should().Be(1);
        }

        [Fact]
        public void ShouldDetectExpectedArgumentAndActualWithMethodTestStormPetrel()
        {
            //Act
            var actual = TestedClass.TestedMethod1();
            var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
            {
                FilePath = "C:\\temp\\temp.cs",
                ClassName = "AssertionNoExpectedVarTest",
                MethodName = "ShouldDetectExpectedArgumentAndActualWithMethodTest",
                VariablePairCurrentIndex = 0,
                VariablePairsCount = 1,
                Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
                {
                }
            };
            var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
            {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Actual = actual.FooMethod()
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ActualVariablePath = new[]
                {
                    "Test.Integration.XUnit",
                    "AssertionNoExpectedVarTest",
                    "ShouldDetectExpectedArgumentAndActualWithMethodTest"
                },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Expected = 1
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSourceContext()
                {
                    Path = new[]
                    {
                        "experimental-method-body-statement-index:1",
                        "Test.Integration.XUnit",
                        "AssertionNoExpectedVarTest",
                        "ShouldDetectExpectedArgumentAndActualWithMethodTest"
                    },
                    MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSourceMethodInfo()
                    {
                        NodeKind = 8638,
                        NodeIndex = 0,
                        ArgsCount = 0
                    }
                },
                MethodSharedContext = stormPetrelSharedContext
            };
            ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
            //Assert
            actual.FooMethod().Should().Be(1);
        }

        [Fact]
        public void ShouldDetectExpectedArgumentAndActualCouplePropertiesOrMethodsTestStormPetrel()
        {
            //Act
            var actual = TestedClass.TestedMethod1();
            var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
            {
                FilePath = "C:\\temp\\temp.cs",
                ClassName = "AssertionNoExpectedVarTest",
                MethodName = "ShouldDetectExpectedArgumentAndActualCouplePropertiesOrMethodsTest",
                VariablePairCurrentIndex = 0,
                VariablePairsCount = 1,
                Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
                {
                }
            };
            var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
            {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Actual = actual.FooMethod().BlaProperty.OneMoreFooMethod()
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ActualVariablePath = new[]
                {
                    "Test.Integration.XUnit",
                    "AssertionNoExpectedVarTest",
                    "ShouldDetectExpectedArgumentAndActualCouplePropertiesOrMethodsTest"
                },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
                Expected = 1
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
            ,
                ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSourceContext()
                {
                    Path = new[]
                    {
                        "experimental-method-body-statement-index:1",
                        "Test.Integration.XUnit",
                        "AssertionNoExpectedVarTest",
                        "ShouldDetectExpectedArgumentAndActualCouplePropertiesOrMethodsTest"
                    },
                    MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSourceMethodInfo()
                    {
                        NodeKind = 8638,
                        NodeIndex = 0,
                        ArgsCount = 0
                    }
                },
                MethodSharedContext = stormPetrelSharedContext
            };
            ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
            //Assert
            actual.FooMethod().BlaProperty.OneMoreFooMethod().Should().Be(1);
        }
    }
}