// <auto-generated />
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable enable
#endif
using FluentAssertions;

namespace Test.Integration.XUnit;
[global::System.CodeDom.Compiler.GeneratedCode("Scand.StormPetrel.Generator", "2.7.0")]
/// <summary>
/// (actualResult, expected) names used in this class tests do not match "TestVariablePairConfigs" regex values.
/// It allows Storm Petrel to analyze invocation paths of the `expected` variable/argument in the assertion expressions.
/// Other variable names can be used here instead of (actualResult, expected) pair or even an expression can be used instead of `actualResult` variable.
/// </summary>
public sealed class AssertInvocationPathTestStormPetrel
{
    [Fact]
    public void WhenAssertIndividualExpectedPropertiesOfLocalVarDeclarationThenShouldUpdateThemTestStormPetrel()
    {
        //Arrange
        var expected = new AddResult
        {
            Value = 5,
            ValueAsHexString = "0x5 - Incorrect",
        };
        //Act
        var actualResult = Calculator.Add(2, 2);
        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "AssertInvocationPathTest",
            MethodName = "WhenAssertIndividualExpectedPropertiesOfLocalVarDeclarationThenShouldUpdateThemTest",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 3,
            Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
            {
            }
        };
        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actualResult.Value
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = expected.Value
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExpectedVariablePath = new[]
            {
                "AssertInvocationPathTest",
                "WhenAssertIndividualExpectedPropertiesOfLocalVarDeclarationThenShouldUpdateThemTest",
                "expected"
            },
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InitializerContext()
            {
                InvocationPath = new[]
                {
                    "Value"
                },
                Kind = Scand.StormPetrel.Generator.Abstraction.ExtraContext.InitializerContextKind.VariableDeclaration
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext1 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actualResult.ValueAsHexString
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = expected.ValueAsHexString
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExpectedVariablePath = new[]
            {
                "AssertInvocationPathTest",
                "WhenAssertIndividualExpectedPropertiesOfLocalVarDeclarationThenShouldUpdateThemTest",
                "expected"
            },
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InitializerContext()
            {
                InvocationPath = new[]
                {
                    "ValueAsHexString"
                },
                Kind = Scand.StormPetrel.Generator.Abstraction.ExtraContext.InitializerContextKind.VariableDeclaration
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext1);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext2 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actualResult.ValueAsHexString.Length
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = expected.ValueAsHexString.Length
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExpectedVariablePath = new[]
            {
                "AssertInvocationPathTest",
                "WhenAssertIndividualExpectedPropertiesOfLocalVarDeclarationThenShouldUpdateThemTest",
                "expected"
            },
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InitializerContext()
            {
                InvocationPath = new[]
                {
                    "ValueAsHexString",
                    "Length"
                },
                Kind = Scand.StormPetrel.Generator.Abstraction.ExtraContext.InitializerContextKind.VariableDeclaration
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext2);
        //Assert
        actualResult.Value.Should().Be(expected.Value);
        actualResult.ValueAsHexString.Should().Be(expected.ValueAsHexString);
        // The following assertion will not update Length property or field in the baseline because it is not explicitely mentioned in expected assignment above.
        // So, we do not generate Length property because its actual semantic may be "getter only".
        actualResult.ValueAsHexString.Length.Should().Be(expected.ValueAsHexString.Length);
        // The following assertions will not update the type of actualResult in the baseline because expected expressions contain a method call.
        actualResult.GetType().Should().Be(expected.GetType());
        actualResult.GetType().FullName.Should().Be(expected.GetType().FullName);
    }

    [Fact]
    public void WhenAssertIndividualExpectedPropertiesOfLocalVarAssignmentThenShouldUpdateThemTestStormPetrel()
    {
        //Arrange
        AddResult expected;
        expected = new AddResult()
        {
            Value = 5,
            ValueAsHexString = "0x5 - Incorrect",
        };
        //Act
        var actualResult = Calculator.Add(2, 2);
        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "AssertInvocationPathTest",
            MethodName = "WhenAssertIndividualExpectedPropertiesOfLocalVarAssignmentThenShouldUpdateThemTest",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 2,
            Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
            {
            }
        };
        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actualResult.Value
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = expected.Value
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExpectedVariablePath = new[]
            {
                "AssertInvocationPathTest",
                "WhenAssertIndividualExpectedPropertiesOfLocalVarAssignmentThenShouldUpdateThemTest",
                "expected"
            },
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InitializerContext()
            {
                InvocationPath = new[]
                {
                    "Value"
                },
                Kind = Scand.StormPetrel.Generator.Abstraction.ExtraContext.InitializerContextKind.VariableAssignment
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext1 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actualResult.ValueAsHexString
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = expected.ValueAsHexString
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExpectedVariablePath = new[]
            {
                "AssertInvocationPathTest",
                "WhenAssertIndividualExpectedPropertiesOfLocalVarAssignmentThenShouldUpdateThemTest",
                "expected"
            },
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InitializerContext()
            {
                InvocationPath = new[]
                {
                    "ValueAsHexString"
                },
                Kind = Scand.StormPetrel.Generator.Abstraction.ExtraContext.InitializerContextKind.VariableAssignment
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext1);
        //Assert
        actualResult.Value.Should().Be(expected.Value);
        actualResult.ValueAsHexString.Should().Be(expected.ValueAsHexString);
    }

    [Theory]
    [MemberData(nameof(TheoryDataSource))]
    public static void WhenTheoryDataSourceThenShouldUpdateItTestStormPetrel(int a, int b, AddResult? expected)
    {
        ArgumentNullException.ThrowIfNull(expected);
        //Arrange
        //Act
        var actualResult = Calculator.Add(a, b);
        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "AssertInvocationPathTest",
            MethodName = "WhenTheoryDataSourceThenShouldUpdateItTest",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 3,
            Parameters = new[]
            {
                new Scand.StormPetrel.Generator.Abstraction.ParameterInfo()
                {
                    Name = "a",
                    Value = a,
                    Attributes = new Scand.StormPetrel.Generator.Abstraction.AttributeInfo[]
                    {
                    },
                    TypeToken = "int"
                },
                new Scand.StormPetrel.Generator.Abstraction.ParameterInfo()
                {
                    Name = "b",
                    Value = b,
                    Attributes = new Scand.StormPetrel.Generator.Abstraction.AttributeInfo[]
                    {
                    },
                    TypeToken = "int"
                },
                new Scand.StormPetrel.Generator.Abstraction.ParameterInfo()
                {
                    Name = "expected",
                    Value = expected,
                    Attributes = new Scand.StormPetrel.Generator.Abstraction.AttributeInfo[]
                    {
                    },
                    TypeToken = "AddResult?"
                }
            }
        };
        var stormPetrelTestCaseSourceRowIndex = -1;
        var stormPetrelIsTestCaseSourceRowExist = false;
        var stormPetrelRows = Scand.StormPetrel.Rewriter.DataSourceHelper.ConvertToStormPetrelRows(Scand.StormPetrel.Rewriter.DataSourceHelper.Enumerate(typeof(AssertInvocationPathTest), nameof(TheoryDataSource)));
        foreach (var stormPetrelRow in stormPetrelRows)
        {
            stormPetrelTestCaseSourceRowIndex++;
            if ((stormPetrelRow.Length > 0 && (a == (int)stormPetrelRow[0] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(a, stormPetrelRow[0]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(a, stormPetrelRow[0])) || stormPetrelRow.Length <= 0 && a == default(int)) && (stormPetrelRow.Length > 1 && (b == (int)stormPetrelRow[1] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(b, stormPetrelRow[1]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(b, stormPetrelRow[1])) || stormPetrelRow.Length <= 1 && b == default(int)))
            {
                stormPetrelIsTestCaseSourceRowExist = true;
                break;
            }
        }

        if (!stormPetrelIsTestCaseSourceRowExist)
        {
            var stormPetrelNoEqualArgNames = new System.Collections.Generic.List<string>()
            {
                "a",
                "b"
            };
            foreach (var stormPetrelRow in stormPetrelRows)
            {
                if (stormPetrelRow.Length > 0 && (a == (int)stormPetrelRow[0] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(a, stormPetrelRow[0]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(a, stormPetrelRow[0])) || stormPetrelRow.Length <= 0 && a == default(int))
                {
                    stormPetrelNoEqualArgNames.Remove("a");
                }

                if (stormPetrelRow.Length > 1 && (b == (int)stormPetrelRow[1] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(b, stormPetrelRow[1]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(b, stormPetrelRow[1])) || stormPetrelRow.Length <= 1 && b == default(int))
                {
                    stormPetrelNoEqualArgNames.Remove("b");
                }
            }

            throw new System.InvalidOperationException("Cannot detect appropriate test case source row to rewrite. Test method argument(s) giving the failure: '" + string.Join("', '", stormPetrelNoEqualArgNames) + "'. To understand the failure root cause you can debug the conditions above returning unexpected value for the argument(s).");
        }

        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actualResult.Value
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = expected!.Value
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.TestCaseSourceContext()
            {
                ColumnIndex = 2,
                RowIndex = stormPetrelTestCaseSourceRowIndex,
                Path = Scand.StormPetrel.Rewriter.DataSourceHelper.GetPath(typeof(AssertInvocationPathTest), nameof(TheoryDataSource)),
                InvocationPath = new[]
                {
                    "Value"
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelTestCaseSourceRowIndex1 = -1;
        var stormPetrelIsTestCaseSourceRowExist1 = false;
        var stormPetrelRows1 = Scand.StormPetrel.Rewriter.DataSourceHelper.ConvertToStormPetrelRows(Scand.StormPetrel.Rewriter.DataSourceHelper.Enumerate(typeof(AssertInvocationPathTest), nameof(TheoryDataSource)));
        foreach (var stormPetrelRow in stormPetrelRows1)
        {
            stormPetrelTestCaseSourceRowIndex1++;
            if ((stormPetrelRow.Length > 0 && (a == (int)stormPetrelRow[0] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(a, stormPetrelRow[0]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(a, stormPetrelRow[0])) || stormPetrelRow.Length <= 0 && a == default(int)) && (stormPetrelRow.Length > 1 && (b == (int)stormPetrelRow[1] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(b, stormPetrelRow[1]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(b, stormPetrelRow[1])) || stormPetrelRow.Length <= 1 && b == default(int)))
            {
                stormPetrelIsTestCaseSourceRowExist1 = true;
                break;
            }
        }

        if (!stormPetrelIsTestCaseSourceRowExist1)
        {
            var stormPetrelNoEqualArgNames1 = new System.Collections.Generic.List<string>()
            {
                "a",
                "b"
            };
            foreach (var stormPetrelRow in stormPetrelRows1)
            {
                if (stormPetrelRow.Length > 0 && (a == (int)stormPetrelRow[0] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(a, stormPetrelRow[0]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(a, stormPetrelRow[0])) || stormPetrelRow.Length <= 0 && a == default(int))
                {
                    stormPetrelNoEqualArgNames1.Remove("a");
                }

                if (stormPetrelRow.Length > 1 && (b == (int)stormPetrelRow[1] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(b, stormPetrelRow[1]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(b, stormPetrelRow[1])) || stormPetrelRow.Length <= 1 && b == default(int))
                {
                    stormPetrelNoEqualArgNames1.Remove("b");
                }
            }

            throw new System.InvalidOperationException("Cannot detect appropriate test case source row to rewrite. Test method argument(s) giving the failure: '" + string.Join("', '", stormPetrelNoEqualArgNames1) + "'. To understand the failure root cause you can debug the conditions above returning unexpected value for the argument(s).");
        }

        var stormPetrelContext1 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actualResult.ValueAsHexString.Length
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = expected.ValueAsHexString.Length
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.TestCaseSourceContext()
            {
                ColumnIndex = 2,
                RowIndex = stormPetrelTestCaseSourceRowIndex1,
                Path = Scand.StormPetrel.Rewriter.DataSourceHelper.GetPath(typeof(AssertInvocationPathTest), nameof(TheoryDataSource)),
                InvocationPath = new[]
                {
                    "ValueAsHexString",
                    "Length"
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext1);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelTestCaseSourceRowIndex2 = -1;
        var stormPetrelIsTestCaseSourceRowExist2 = false;
        var stormPetrelRows2 = Scand.StormPetrel.Rewriter.DataSourceHelper.ConvertToStormPetrelRows(Scand.StormPetrel.Rewriter.DataSourceHelper.Enumerate(typeof(AssertInvocationPathTest), nameof(TheoryDataSource)));
        foreach (var stormPetrelRow in stormPetrelRows2)
        {
            stormPetrelTestCaseSourceRowIndex2++;
            if ((stormPetrelRow.Length > 0 && (a == (int)stormPetrelRow[0] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(a, stormPetrelRow[0]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(a, stormPetrelRow[0])) || stormPetrelRow.Length <= 0 && a == default(int)) && (stormPetrelRow.Length > 1 && (b == (int)stormPetrelRow[1] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(b, stormPetrelRow[1]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(b, stormPetrelRow[1])) || stormPetrelRow.Length <= 1 && b == default(int)))
            {
                stormPetrelIsTestCaseSourceRowExist2 = true;
                break;
            }
        }

        if (!stormPetrelIsTestCaseSourceRowExist2)
        {
            var stormPetrelNoEqualArgNames2 = new System.Collections.Generic.List<string>()
            {
                "a",
                "b"
            };
            foreach (var stormPetrelRow in stormPetrelRows2)
            {
                if (stormPetrelRow.Length > 0 && (a == (int)stormPetrelRow[0] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(a, stormPetrelRow[0]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(a, stormPetrelRow[0])) || stormPetrelRow.Length <= 0 && a == default(int))
                {
                    stormPetrelNoEqualArgNames2.Remove("a");
                }

                if (stormPetrelRow.Length > 1 && (b == (int)stormPetrelRow[1] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(b, stormPetrelRow[1]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(b, stormPetrelRow[1])) || stormPetrelRow.Length <= 1 && b == default(int))
                {
                    stormPetrelNoEqualArgNames2.Remove("b");
                }
            }

            throw new System.InvalidOperationException("Cannot detect appropriate test case source row to rewrite. Test method argument(s) giving the failure: '" + string.Join("', '", stormPetrelNoEqualArgNames2) + "'. To understand the failure root cause you can debug the conditions above returning unexpected value for the argument(s).");
        }

        var stormPetrelContext2 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actualResult.ValueAsHexString
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = expected?.ValueAsHexString!
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.TestCaseSourceContext()
            {
                ColumnIndex = 2,
                RowIndex = stormPetrelTestCaseSourceRowIndex2,
                Path = Scand.StormPetrel.Rewriter.DataSourceHelper.GetPath(typeof(AssertInvocationPathTest), nameof(TheoryDataSource)),
                InvocationPath = new[]
                {
                    "ValueAsHexString"
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext2);
        //Assert
        actualResult.Value.Should().Be(expected!.Value);
        actualResult.ValueAsHexString.Length.Should().Be(expected.ValueAsHexString.Length);
        actualResult.ValueAsHexString.Should().Be(expected?.ValueAsHexString!);
    }

    [Theory]
    [MemberData(nameof(TheoryDataSourceForNoActualVariable))]
    public static void WhenAnExpressionInsteadOfActualVariableThenShouldUpdateItTestStormPetrel(int a, int b, AddResult? myExp)
    {
        ArgumentNullException.ThrowIfNull(myExp);
        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "AssertInvocationPathTest",
            MethodName = "WhenAnExpressionInsteadOfActualVariableThenShouldUpdateItTest",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 2,
            Parameters = new[]
            {
                new Scand.StormPetrel.Generator.Abstraction.ParameterInfo()
                {
                    Name = "a",
                    Value = a,
                    Attributes = new Scand.StormPetrel.Generator.Abstraction.AttributeInfo[]
                    {
                    },
                    TypeToken = "int"
                },
                new Scand.StormPetrel.Generator.Abstraction.ParameterInfo()
                {
                    Name = "b",
                    Value = b,
                    Attributes = new Scand.StormPetrel.Generator.Abstraction.AttributeInfo[]
                    {
                    },
                    TypeToken = "int"
                },
                new Scand.StormPetrel.Generator.Abstraction.ParameterInfo()
                {
                    Name = "myExp",
                    Value = myExp,
                    Attributes = new Scand.StormPetrel.Generator.Abstraction.AttributeInfo[]
                    {
                    },
                    TypeToken = "AddResult?"
                }
            }
        };
        var stormPetrelTestCaseSourceRowIndex = -1;
        var stormPetrelIsTestCaseSourceRowExist = false;
        var stormPetrelRows = Scand.StormPetrel.Rewriter.DataSourceHelper.ConvertToStormPetrelRows(Scand.StormPetrel.Rewriter.DataSourceHelper.Enumerate(typeof(AssertInvocationPathTest), nameof(TheoryDataSourceForNoActualVariable)));
        foreach (var stormPetrelRow in stormPetrelRows)
        {
            stormPetrelTestCaseSourceRowIndex++;
            if ((stormPetrelRow.Length > 0 && (a == (int)stormPetrelRow[0] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(a, stormPetrelRow[0]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(a, stormPetrelRow[0])) || stormPetrelRow.Length <= 0 && a == default(int)) && (stormPetrelRow.Length > 1 && (b == (int)stormPetrelRow[1] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(b, stormPetrelRow[1]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(b, stormPetrelRow[1])) || stormPetrelRow.Length <= 1 && b == default(int)))
            {
                stormPetrelIsTestCaseSourceRowExist = true;
                break;
            }
        }

        if (!stormPetrelIsTestCaseSourceRowExist)
        {
            var stormPetrelNoEqualArgNames = new System.Collections.Generic.List<string>()
            {
                "a",
                "b"
            };
            foreach (var stormPetrelRow in stormPetrelRows)
            {
                if (stormPetrelRow.Length > 0 && (a == (int)stormPetrelRow[0] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(a, stormPetrelRow[0]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(a, stormPetrelRow[0])) || stormPetrelRow.Length <= 0 && a == default(int))
                {
                    stormPetrelNoEqualArgNames.Remove("a");
                }

                if (stormPetrelRow.Length > 1 && (b == (int)stormPetrelRow[1] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(b, stormPetrelRow[1]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(b, stormPetrelRow[1])) || stormPetrelRow.Length <= 1 && b == default(int))
                {
                    stormPetrelNoEqualArgNames.Remove("b");
                }
            }

            throw new System.InvalidOperationException("Cannot detect appropriate test case source row to rewrite. Test method argument(s) giving the failure: '" + string.Join("', '", stormPetrelNoEqualArgNames) + "'. To understand the failure root cause you can debug the conditions above returning unexpected value for the argument(s).");
        }

        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = Calculator.Add(a, b).Value
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = myExp!.Value
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.TestCaseSourceContext()
            {
                ColumnIndex = 2,
                RowIndex = stormPetrelTestCaseSourceRowIndex,
                Path = Scand.StormPetrel.Rewriter.DataSourceHelper.GetPath(typeof(AssertInvocationPathTest), nameof(TheoryDataSourceForNoActualVariable)),
                InvocationPath = new[]
                {
                    "Value"
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelTestCaseSourceRowIndex1 = -1;
        var stormPetrelIsTestCaseSourceRowExist1 = false;
        var stormPetrelRows1 = Scand.StormPetrel.Rewriter.DataSourceHelper.ConvertToStormPetrelRows(Scand.StormPetrel.Rewriter.DataSourceHelper.Enumerate(typeof(AssertInvocationPathTest), nameof(TheoryDataSourceForNoActualVariable)));
        foreach (var stormPetrelRow in stormPetrelRows1)
        {
            stormPetrelTestCaseSourceRowIndex1++;
            if ((stormPetrelRow.Length > 0 && (a == (int)stormPetrelRow[0] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(a, stormPetrelRow[0]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(a, stormPetrelRow[0])) || stormPetrelRow.Length <= 0 && a == default(int)) && (stormPetrelRow.Length > 1 && (b == (int)stormPetrelRow[1] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(b, stormPetrelRow[1]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(b, stormPetrelRow[1])) || stormPetrelRow.Length <= 1 && b == default(int)))
            {
                stormPetrelIsTestCaseSourceRowExist1 = true;
                break;
            }
        }

        if (!stormPetrelIsTestCaseSourceRowExist1)
        {
            var stormPetrelNoEqualArgNames1 = new System.Collections.Generic.List<string>()
            {
                "a",
                "b"
            };
            foreach (var stormPetrelRow in stormPetrelRows1)
            {
                if (stormPetrelRow.Length > 0 && (a == (int)stormPetrelRow[0] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(a, stormPetrelRow[0]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(a, stormPetrelRow[0])) || stormPetrelRow.Length <= 0 && a == default(int))
                {
                    stormPetrelNoEqualArgNames1.Remove("a");
                }

                if (stormPetrelRow.Length > 1 && (b == (int)stormPetrelRow[1] || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEqual(b, stormPetrelRow[1]) || Scand.StormPetrel.Rewriter.DataSourceHelper.AreEnumerablesOfEqualElements(b, stormPetrelRow[1])) || stormPetrelRow.Length <= 1 && b == default(int))
                {
                    stormPetrelNoEqualArgNames1.Remove("b");
                }
            }

            throw new System.InvalidOperationException("Cannot detect appropriate test case source row to rewrite. Test method argument(s) giving the failure: '" + string.Join("', '", stormPetrelNoEqualArgNames1) + "'. To understand the failure root cause you can debug the conditions above returning unexpected value for the argument(s).");
        }

        var stormPetrelContext1 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = Calculator.Add(a, b).ValueAsHexString
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = myExp?.ValueAsHexString!
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.TestCaseSourceContext()
            {
                ColumnIndex = 2,
                RowIndex = stormPetrelTestCaseSourceRowIndex1,
                Path = Scand.StormPetrel.Rewriter.DataSourceHelper.GetPath(typeof(AssertInvocationPathTest), nameof(TheoryDataSourceForNoActualVariable)),
                InvocationPath = new[]
                {
                    "ValueAsHexString"
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext1);
        Calculator.Add(a, b).Value.Should().Be(myExp!.Value);
        Calculator.Add(a, b).ValueAsHexString.Should().Be(myExp?.ValueAsHexString!);
    }

    public static TheoryData<int, int, AddResult> TheoryDataSource => new()
    {
        {
            2,
            2,
            new AddResult()
            {
                Value = 5,
                ValueAsHexString = "0x5 - Incorrect",
            }
        },
        {
            -2,
            10,
            new()
            {
                Value = 5,
                ValueAsHexString = "0x5 - Incorrect",
            }
        },
        {
            -2,
            -2,
            new AddResult
            {
                Value = 5,
                ValueAsHexString = "0x5 - Incorrect",
            }
        },
    };
    public static TheoryData<int, int, AddResult> TheoryDataSourceForNoActualVariable => new()
    {
        {
            2,
            2,
            new AddResult()
            {
                Value = 5,
                ValueAsHexString = "0x5 - Incorrect",
            }
        },
    };
}