// <auto-generated />
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable enable
#endif
//#if DEBUG
namespace Test.Integration.ObjectDumper.XUnit;
// Commented out for partial classes to avoid CS0579 error
// [global::System.CodeDom.Compiler.GeneratedCode("Scand.StormPetrel.Generator", "2.7.0")]
public static partial class IgnoreInDebugStormPetrel
{
    public static int TestDataSourceCandidate() => EnsureProperIgnoreFilePathRegexIsAppliedConstant;
    public static (int NodeKind, int NodeIndex) TestDataSourceCandidateStormPetrel() => (8917, 0);
}//#endif
