// <auto-generated />
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable enable
#endif
using Shouldly;
using System.Globalization;

namespace Test.Integration.XUnit;
[global::System.CodeDom.Compiler.GeneratedCode("Scand.StormPetrel.Generator", "2.7.0")]
public class NoExpectedVarShouldlyTestStormPetrel
{
    [Fact]
    public void ShouldBeTestStormPetrel()
    {
        //Act
        var actual = TestedClass.TestedMethod();
        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "NoExpectedVarShouldlyTest",
            MethodName = "ShouldBeTest",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 1,
            Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
            {
            }
        };
        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = 123
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 1
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        //Assert
        actual.ShouldBe(123);
    }

    [Fact]
    public void ShouldDetectExpectedArgumentWhenMultipleArgsTestStormPetrel()
    {
        //Act
        var actual = TestedClass.TestedMethod();
        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "NoExpectedVarShouldlyTest",
            MethodName = "ShouldDetectExpectedArgumentWhenMultipleArgsTest",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 2,
            Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
            {
            }
        };
        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldDetectExpectedArgumentWhenMultipleArgsTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = 123
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldDetectExpectedArgumentWhenMultipleArgsTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 1
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext1 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldDetectExpectedArgumentWhenMultipleArgsTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = 123
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldDetectExpectedArgumentWhenMultipleArgsTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 1,
                    StatementIndex = 2
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext1);
        //Assert
        actual.ShouldBe(123, "some explanation");
        actual.ShouldBe(customMessage: "some explanation", expected: 123);
    }

    [Fact]
    public void ShouldDetectExpectedArgumentAndActualWithPropertyTestStormPetrel()
    {
        //Act
        var actual = TestedClass.TestedClassResultMethod();
        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "NoExpectedVarShouldlyTest",
            MethodName = "ShouldDetectExpectedArgumentAndActualWithPropertyTest",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 1,
            Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
            {
            }
        };
        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual.IntProperty
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldDetectExpectedArgumentAndActualWithPropertyTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = 123
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldDetectExpectedArgumentAndActualWithPropertyTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 1
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        //Assert
        actual.IntProperty.ShouldBe(123);
    }

    [Fact]
    public void ShouldDetectExpectedArgumentAndActualWithMethodTestStormPetrel()
    {
        //Act
        var actual = TestedClass.TestedClassResultMethod();
        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "NoExpectedVarShouldlyTest",
            MethodName = "ShouldDetectExpectedArgumentAndActualWithMethodTest",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 1,
            Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
            {
            }
        };
        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual.IntPropertyAsMethod()
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldDetectExpectedArgumentAndActualWithMethodTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = 123
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldDetectExpectedArgumentAndActualWithMethodTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 1
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        //Assert
        actual.IntPropertyAsMethod().ShouldBe(123);
    }

    [Fact]
    public void ShouldBeWhenMultipleActualsTestStormPetrel()
    {
        //Act
        var actual = TestedClass.TestedMethod();
        var actual2 = 100;
        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "NoExpectedVarShouldlyTest",
            MethodName = "ShouldBeWhenMultipleActualsTest",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 2,
            Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
            {
            }
        };
        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenMultipleActualsTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = 123
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenMultipleActualsTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 2
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext1 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual2
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenMultipleActualsTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = 123
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenMultipleActualsTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 3
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext1);
        //Assert
        actual.ShouldBe(123);
        actual2.ShouldBe(123);
    }

    [Fact]
    public void ShouldBeWhithInvocationExpressionTest()
    {
        //Act
        var actual = TestedClass.TestedMethod();
        //Assert
        //The assertion does not fail by default. Also, StormPetrel does not replace the invocation expression below.
        //But we keep this use case to indicate no unexpected failures in StormPetrel here.
        actual.ShouldBe(TestedClass.TestedMethod());
        actual.ShouldBe(TestedClass.ReturnInput(TestedClass.TestedMethod()));
    }

    [Fact]
    public void ShouldBeWhenNullConditionalOperatorTestStormPetrel()
    {
        //Act
        var actual = TestedClass.TestedClassResultMethod();
        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "NoExpectedVarShouldlyTest",
            MethodName = "ShouldBeWhenNullConditionalOperatorTest",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 5,
            Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
            {
            }
        };
        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual?.StringNullableProperty
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullConditionalOperatorTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = "Incorrect value"
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullConditionalOperatorTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 1
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext1 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual?.StringNullableProperty
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullConditionalOperatorTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = null
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullConditionalOperatorTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 2
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext1);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext2 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual?.StringNullableProperty
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullConditionalOperatorTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = "Incorrect value"
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullConditionalOperatorTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 3
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext2);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext3 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual?.StringNullablePropertyAsMethod()
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullConditionalOperatorTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = "Incorrect value"
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullConditionalOperatorTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 4
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext3);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext4 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual.StringNullableProperty
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullConditionalOperatorTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = "Incorrect value"
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullConditionalOperatorTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 6
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext4);
        //Assert
        actual?.StringNullableProperty.ShouldBe("Incorrect value");
        actual?.StringNullableProperty.ShouldBe(null);
        actual?.StringNullableProperty?.ShouldBe("Incorrect value");
        actual?.StringNullablePropertyAsMethod()?.ShouldBe("Incorrect value");
        ArgumentNullException.ThrowIfNull(actual);
        actual.StringNullableProperty?.ShouldBe("Incorrect value");
    }

    [Fact]
    public void ShouldBeWhenNullConditionalOperatorAssertsNullTestStormPetrel()
    {
        //Act
        var actual = TestedClass.TestedClassResultMethod();
        actual.StringNullableProperty = null;
        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "NoExpectedVarShouldlyTest",
            MethodName = "ShouldBeWhenNullConditionalOperatorAssertsNullTest",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 5,
            Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
            {
            }
        };
        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual?.StringNullableProperty
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullConditionalOperatorAssertsNullTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = "Incorrect not null"
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullConditionalOperatorAssertsNullTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 2
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext1 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual?.StringNullableProperty
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullConditionalOperatorAssertsNullTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = null
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullConditionalOperatorAssertsNullTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 3
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext1);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext2 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual?.StringNullableProperty
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullConditionalOperatorAssertsNullTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = "Incorrect not null"
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullConditionalOperatorAssertsNullTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 4
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext2);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext3 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual?.StringNullablePropertyAsMethod()
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullConditionalOperatorAssertsNullTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = "Incorrect not null"
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullConditionalOperatorAssertsNullTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 5
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext3);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext4 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual.StringNullableProperty
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullConditionalOperatorAssertsNullTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = "Incorrect not null"
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullConditionalOperatorAssertsNullTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 7
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext4);
        //Assert
        /*Test comment*/
        actual?.StringNullableProperty.ShouldBe("Incorrect not null");
        //Test comment
        actual?.StringNullableProperty.ShouldBe(null);
        //Test multiline
        //comment
        actual?.StringNullableProperty?.ShouldBe("Incorrect not null");
        /*Test comment*/
        actual?.StringNullablePropertyAsMethod()?.ShouldBe("Incorrect not null");
        ArgumentNullException.ThrowIfNull(actual);
        /*Test multiline
         *comment*/
        actual.StringNullableProperty?.ShouldBe("Incorrect not null");
    }

    [Fact]
    public void ShouldBeWhenNullForgivenOperatorTestStormPetrel()
    {
        //Act
        var actual = TestedClass.TestedClassResultMethod();
        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "NoExpectedVarShouldlyTest",
            MethodName = "ShouldBeWhenNullForgivenOperatorTest",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 5,
            Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
            {
            }
        };
        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual!.StringNullableProperty
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullForgivenOperatorTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = "Incorrect value"
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullForgivenOperatorTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 1
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext1 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual!.StringNullableProperty
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullForgivenOperatorTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = null
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullForgivenOperatorTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 2
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext1);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext2 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual!.StringNullableProperty!
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullForgivenOperatorTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = "Incorrect value"
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullForgivenOperatorTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 3
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext2);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext3 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual!.StringNullablePropertyAsMethod()!
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullForgivenOperatorTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = "Incorrect value"
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullForgivenOperatorTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 4
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext3);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext4 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual.StringNullableProperty!
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullForgivenOperatorTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = "Incorrect value"
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullForgivenOperatorTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 6
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext4);
        //Assert
        actual!.StringNullableProperty.ShouldBe("Incorrect value");
        actual!.StringNullableProperty.ShouldBe(null);
        actual!.StringNullableProperty!.ShouldBe("Incorrect value");
        actual!.StringNullablePropertyAsMethod()!.ShouldBe("Incorrect value");
        ArgumentNullException.ThrowIfNull(actual);
        actual.StringNullableProperty!.ShouldBe("Incorrect value");
    }

    [Fact]
    public void ShouldBeWhenNullCoalescingOperatorTestStormPetrel()
    {
        //Act
        var actual = TestedClass.TestedClassResultMethod();
        if (actual == null)
        {
            throw new InvalidOperationException();
        }

        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "NoExpectedVarShouldlyTest",
            MethodName = "ShouldBeWhenNullCoalescingOperatorTest",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 5,
            Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
            {
            }
        };
        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual.StringNullableProperty
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullCoalescingOperatorTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = "Incorrect value"
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullCoalescingOperatorTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 2
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext1 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual.StringNullableProperty
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullCoalescingOperatorTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = null
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullCoalescingOperatorTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 3
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext1);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext2 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual.StringNullableProperty
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullCoalescingOperatorTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = "Incorrect value"
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullCoalescingOperatorTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 4
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext2);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext3 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = (actual.StringNullablePropertyAsMethod() ?? throw new InvalidOperationException())
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullCoalescingOperatorTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = "Incorrect value"
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullCoalescingOperatorTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 5
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext3);
        stormPetrelSharedContext.VariablePairCurrentIndex++;
        var stormPetrelContext4 = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = (actual.StringNullableProperty ?? throw new InvalidOperationException())
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeWhenNullCoalescingOperatorTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = "Incorrect value"
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeWhenNullCoalescingOperatorTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 6
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext4);
        //Assert
        actual.StringNullableProperty.ShouldBe("Incorrect value");
        actual.StringNullableProperty.ShouldBe(null);
        actual.StringNullableProperty?.ShouldBe("Incorrect value");
        (actual.StringNullablePropertyAsMethod() ?? throw new InvalidOperationException()).ShouldBe("Incorrect value");
        (actual.StringNullableProperty ?? throw new InvalidOperationException()).ShouldBe("Incorrect value");
    }

    [Fact]
    public void ShouldBeDetectExpectedArgumentWhenAnonymousObjectCreationTestStormPetrel()
    {
        //Act
        var actual = new
        {
            Amount = 100,
            Message = "Hello"
        };
        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "NoExpectedVarShouldlyTest",
            MethodName = "ShouldBeDetectExpectedArgumentWhenAnonymousObjectCreationTest",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 1,
            Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
            {
            }
        };
        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeDetectExpectedArgumentWhenAnonymousObjectCreationTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = new
            {
                Amount = 123,
                Message = "Hello incorrect"
            }
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeDetectExpectedArgumentWhenAnonymousObjectCreationTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 1
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        //Assert
        actual.ShouldBe(new { Amount = 123, Message = "Hello incorrect" });
    }

    [Fact]
    public void ShouldBeDetectExpectedArgumentWhenLiteralExpressionSyntaxTestStormPetrel()
    {
        //Act
        var actual = 100;
        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "NoExpectedVarShouldlyTest",
            MethodName = "ShouldBeDetectExpectedArgumentWhenLiteralExpressionSyntaxTest",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 1,
            Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
            {
            }
        };
        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeDetectExpectedArgumentWhenLiteralExpressionSyntaxTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = 123
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeDetectExpectedArgumentWhenLiteralExpressionSyntaxTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 1
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        //Assert
        actual.ShouldBe(123);
    }

    [Fact]
    public void ShouldBeDetectExpectedArgumentWhenLiteralExpressionSyntaxStringTestStormPetrel()
    {
        //Act
        var actual = "Hello, World incorrect!";
        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "NoExpectedVarShouldlyTest",
            MethodName = "ShouldBeDetectExpectedArgumentWhenLiteralExpressionSyntaxStringTest",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 1,
            Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
            {
            }
        };
        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeDetectExpectedArgumentWhenLiteralExpressionSyntaxStringTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = "Hello, World!"
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeDetectExpectedArgumentWhenLiteralExpressionSyntaxStringTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 1
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        //Assert
        actual.ShouldBe("Hello, World!");
    }

    [Fact]
    public void ShouldBeDetectExpectedArgumentWhenLiteralExpressionSyntaxCharTestStormPetrel()
    {
        //Act
        var actual = 'B';
        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "NoExpectedVarShouldlyTest",
            MethodName = "ShouldBeDetectExpectedArgumentWhenLiteralExpressionSyntaxCharTest",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 1,
            Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
            {
            }
        };
        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeDetectExpectedArgumentWhenLiteralExpressionSyntaxCharTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = 'A'
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeDetectExpectedArgumentWhenLiteralExpressionSyntaxCharTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 1
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        //Assert
        actual.ShouldBe('A');
    }

    [Fact]
    public void ShouldBeDetectExpectedAndActualWhenComparerUsedTestStormPetrel()
    {
        //Act
        var actual = TestedClass.TestedClassResultMethod();
        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "NoExpectedVarShouldlyTest",
            MethodName = "ShouldBeDetectExpectedAndActualWhenComparerUsedTest",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 1,
            Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
            {
            }
        };
        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "ShouldBeDetectExpectedAndActualWhenComparerUsedTest"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = new TestClassResult
            {
                IntProperty = 123,
                DateTimeProperty = DateTime.ParseExact("2025-03-17T18:11:00.0000000", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
            }
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "ShouldBeDetectExpectedAndActualWhenComparerUsedTest"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 1
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        //Assert
        actual.ShouldBe(new TestClassResult { IntProperty = 123, DateTimeProperty = DateTime.ParseExact("2025-03-17T18:11:00.0000000", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind), }, new TestClassResultEqualityComparer());
    }

    [Fact]
    public void WhenShouldBeEquivalentToStormPetrel()
    {
        //Act
        var actual = Calculator.Add(2, 2);
        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "NoExpectedVarShouldlyTest",
            MethodName = "WhenShouldBeEquivalentTo",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 1,
            Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
            {
            }
        };
        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "WhenShouldBeEquivalentTo"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = new()
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "WhenShouldBeEquivalentTo"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 0,
                    StatementIndex = 1
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        //Assert
        actual.ShouldBeEquivalentTo(new());
    }

    [Fact]
    public void WhenShouldBeEquivalentToWithNamedArgsStormPetrel()
    {
        //Act
        int[] actual = [1, 2, 3];
        var stormPetrelSharedContext = new Scand.StormPetrel.Generator.Abstraction.MethodContext()
        {
            FilePath = "C:\\temp\\temp.cs",
            ClassName = "NoExpectedVarShouldlyTest",
            MethodName = "WhenShouldBeEquivalentToWithNamedArgs",
            VariablePairCurrentIndex = 0,
            VariablePairsCount = 1,
            Parameters = new Scand.StormPetrel.Generator.Abstraction.ParameterInfo[]
            {
            }
        };
        var stormPetrelContext = new Scand.StormPetrel.Generator.Abstraction.GenerationContext()
        {
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Actual = actual
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ActualVariablePath = new[]
            {
                "NoExpectedVarShouldlyTest",
                "WhenShouldBeEquivalentToWithNamedArgs"
            },
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable disable
#endif
            Expected = new int[]
            {
                3,
                4,
                5
            }
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable restore
#endif
        ,
            ExtraContext = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext()
            {
                Path = new[]
                {
                    "NoExpectedVarShouldlyTest",
                    "WhenShouldBeEquivalentToWithNamedArgs"
                },
                MethodInfo = new Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo()
                {
                    StatementNodeKind = 8638,
                    StatementNodeIndex = 1,
                    StatementIndex = 1
                }
            },
            MethodSharedContext = stormPetrelSharedContext
        };
        ((Scand.StormPetrel.Generator.Abstraction.IGenerator)new Scand.StormPetrel.Generator.TargetProject.Generator()).GenerateBaseline(stormPetrelContext);
        //Assert
        actual.ShouldBeEquivalentTo(customMessage: "Should detect `expected` as a named arg", expected: new int[] { 3, 4, 5 });
    }
}