// <auto-generated />
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable enable
#endif
namespace Test.Integration.XUnit;
// Commented out for partial classes to avoid CS0579 error
// [global::System.CodeDom.Compiler.GeneratedCode("Scand.StormPetrel.Generator", "2.6.0")]
partial class TestCaseSourceMemberDataTestStormPetrel
{
    public static TheoryData<int, int, string> MemberDataInPartialFile() => new()
    {
        {
            1,
            2,
            "0x0"
        },
        {
            -2,
            2,
            "0x0"
        },
        {
            int.MinValue,
            -1,
            "0x0"
        },
        {
            -4,
            -6,
            "0x0"
        },
    };
    public static (int NodeKind, int NodeIndex) MemberDataInPartialFileStormPetrel() => (8917, 0);
    public static TheoryData<int, int, string> MemberDataPropertyInPartialFile => new()
    {
        {
            1,
            2,
            "0x0"
        },
        {
            int.MinValue,
            -1,
            "0x0"
        },
    };
}