// <auto-generated />
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable enable
#endif
using System.Text.Json;

namespace Test.Integration.XUnit;
// Commented out for partial classes to avoid CS0579 error
// [global::System.CodeDom.Compiler.GeneratedCode("Scand.StormPetrel.Generator", "2.7.0")]
partial class UtilsStormPetrel
{
    private readonly static JsonSerializerOptions options = new()
    {
        WriteIndented = false
    };
    public static Exception? SafeExecute(Action action)
    {
        try
        {
            action();
        }
        catch (Exception e)
        {
            return e;
        }

        return null;
    }

    public static (int NodeKind, int NodeIndex) SafeExecuteStormPetrel(Action action)
    {
        try
        {
            action();
        }
        catch (Exception e)
        {
            return (8805, 0);
        }

        return (8805, 1);
    }
}