// <auto-generated />
#if !NETFRAMEWORK || SCAND_STORM_PETREL_NULLABLE_ENABLE
#nullable enable
#endif
using VarDump.Visitor;

namespace Test.Integration.XUnit;
[global::System.CodeDom.Compiler.GeneratedCode("Scand.StormPetrel.Generator", "2.7.0")]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal static partial class UtilsStormPetrel
{
    public static DumpOptions GetDumpOptions()
    {
        var options = new DumpOptions
        {
            Descriptors =
            {
                new IgnoredMembersMiddleware(),
            }
        };
        return options;
    }

    public static (int NodeKind, int NodeIndex) GetDumpOptionsStormPetrel()
    {
        var options = new DumpOptions
        {
            Descriptors =
            {
                new IgnoredMembersMiddleware(),
            }
        };
        return (8805, 0);
    }
}