// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "To simplify test classes", Scope = "member", Target = "~P:Test.Integration.XUnit.TestClassResult.TestClassResultList")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "To simplify test classes", Scope = "member", Target = "~P:Test.Integration.XUnit.TestClassResult.TestClassResultList")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "To simplify test classes", Scope = "member", Target = "~P:Test.Integration.XUnit.TestClassResult.TestClassResultDict")]
[assembly: SuppressMessage("Style", "IDE0074:Use compound assignment", Justification = "We use the code in projects where compound assignment is not supported", Scope = "member", Target = "~M:Test.Integration.Shared.BackupHelper.DeleteBackup(System.String,System.Action{Test.Integration.Shared.BackupHelperResult},System.String,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE0057:Use range operator", Justification = "We use the code in projects where range operator is not supported", Scope = "member", Target = "~M:Test.Integration.Shared.BackupHelper.DeleteBackup(System.String,System.Action{Test.Integration.Shared.BackupHelperResult},System.String,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "We use the code in projects where target-typed new expression is not supported", Scope = "member", Target = "~F:Test.Integration.Shared.BackupHelper.ClassFullNameToLock")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "We use the code in projects where target-typed new expression is not supported", Scope = "member", Target = "~F:Test.Integration.Shared.BackupHelper.ClassFullNameToWasHandled")]
[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "To intentionally test the use case", Scope = "member", Target = "~M:Test.Integration.XUnit.NoExpectedVarExpressionKindsTest.ShouldDetectExpectedArgumentWhenArrayCreationExpressionWithInitializerTest")]
[assembly: SuppressMessage("Style", "IDE0300:Simplify collection initialization", Justification = "To intentionally test the use case", Scope = "member", Target = "~M:Test.Integration.XUnit.NoExpectedVarExpressionKindsTest.ShouldDetectExpectedArgumentWhenArrayCreationExpressionWithInitializerTest")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "To intentionally test the use case", Scope = "member", Target = "~M:Test.Integration.XUnit.NoExpectedVarExpressionKindsTest.ShouldDetectExpectedArgumentWhenArrayCreationExpressionMultidimensionalTest")]
[assembly: SuppressMessage("Style", "IDE0300:Simplify collection initialization", Justification = "To intentionally test the use case", Scope = "member", Target = "~M:Test.Integration.XUnit.NoExpectedVarExpressionKindsTest.ShouldDetectExpectedArgumentWhenImplicitArrayCreationExpressionTest")]
[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "To intentionally test the use case", Scope = "member", Target = "~M:Test.Integration.XUnit.NoExpectedVarExpressionKindsTest.ShouldDetectExpectedArgumentWhenImplicitArrayCreationExpressionTest")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "To intentionally test the use case", Scope = "member", Target = "~M:Test.Integration.XUnit.NoExpectedVarExpressionKindsTest.ShouldDetectExpectedArgumentWhenImplicitArrayCreationExpressionMultiDimensionalTest")]
[assembly: SuppressMessage("Style", "IDE0300:Simplify collection initialization", Justification = "To intentionally test the use case", Scope = "member", Target = "~M:Test.Integration.XUnit.NoExpectedVarExpressionKindsTest.ShouldDetectExpectedArgumentWhenArrayCreationExpressionTest")]
[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "To intentionally test the use case", Scope = "member", Target = "~M:Test.Integration.XUnit.NoExpectedVarExpressionKindsTest.ShouldDetectExpectedArgumentWhenArrayCreationExpressionTest")]
[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "To intentionally test the use case", Scope = "member", Target = "~M:Test.Integration.XUnit.NoExpectedVarExpressionKindsTest.ShouldDetectExpectedArgumentWhenArrayCreationExpressionJaggedTest")]
[assembly: SuppressMessage("Style", "IDE0300:Simplify collection initialization", Justification = "To intentionally test the use case", Scope = "member", Target = "~M:Test.Integration.XUnit.NoExpectedVarExpressionKindsTest.ShouldDetectExpectedArgumentWhenArrayCreationExpressionJaggedTest")]
[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "To intentionally test the use case", Scope = "member", Target = "~M:Test.Integration.XUnit.NoExpectedVarAssertTest.AsyncCollectionAssertsEqualTest")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "To intentionally test the use case", Scope = "member", Target = "~M:Test.Integration.XUnit.Utils.SafeExecute(System.Action)~System.Exception")]
[assembly: SuppressMessage("Maintainability", "CA1508:Avoid dead conditional code", Justification = "To intentionally test the use case", Scope = "member", Target = "~M:Test.Integration.XUnit.NoExpectedVarWithOperatorsTest.WhenNullCoalescingOperatorTest")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "To intentionally test the use case", Scope = "member", Target = "~M:Test.Integration.XUnit.NoExpectedVarAssertTest.AssertJaggedArrayTest")]
[assembly: SuppressMessage("Style", "IDE0300:Simplify collection initialization", Justification = "To intentionally test the use case", Scope = "member", Target = "~M:Test.Integration.XUnit.NoExpectedVarAssertTest.AssertJaggedArrayTest")]
[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "To intentionally test the use case", Scope = "member", Target = "~M:Test.Integration.XUnit.NoExpectedVarAssertTest.AssertJaggedArrayTest")]
