// <auto-generated />
namespace Scand.StormPetrel.Generator.TargetProject
{
    // {GeneratedCodeAttribute}
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed class GeneratorDumper : global::Scand.StormPetrel.Generator.Abstraction.IGeneratorDumper
    {
        private readonly global::VarDump.CSharpDumper _dumper;
        public GeneratorDumper(global::VarDump.CSharpDumper dumper)
        {
            _dumper = dumper;
        }
        public string Dump(global::Scand.StormPetrel.Generator.Abstraction.GenerationDumpContext generationDumpContext)
        {
            string dump = _dumper.Dump(generationDumpContext.Value);
            var i = dump.IndexOf('=');
            if (i < 0)
            {
                throw new global::System.InvalidOperationException("Unexpected index of '='");
            }
            dump = dump
                    .Substring(i + 1)
                    .TrimStart(' ')
                    .TrimEnd('\n', '\r', ';');
            return dump;
        }
    }
}
