// <auto-generated />
namespace Scand.StormPetrel.Generator.TargetProject
{
    partial class Generator
    {
        /// <summary>
        /// To support AOT compilation, we need to ensure that the necessary type information for the types used in reflection code of Scand.StormPetrel.Rewriter is preserved.
        /// </summary>
        static partial void ReferenceNecessaryTypesInfo()
        {
            ReferenceNecessaryTypeInfo(typeof(global::Xunit.TheoryDataRow));
            ReferenceNecessaryTypeInfo(typeof(global::Xunit.TheoryDataRow<>));
            ReferenceNecessaryTypeInfo(typeof(global::Xunit.TheoryDataRow<,>));
            ReferenceNecessaryTypeInfo(typeof(global::Xunit.TheoryDataRow<,,>));
            ReferenceNecessaryTypeInfo(typeof(global::Xunit.TheoryDataRow<,,,>));
            ReferenceNecessaryTypeInfo(typeof(global::Xunit.TheoryDataRow<,,,,>));
            ReferenceNecessaryTypeInfo(typeof(global::Xunit.TheoryDataRow<,,,,,>));
            ReferenceNecessaryTypeInfo(typeof(global::Xunit.TheoryDataRow<,,,,,,>));
            ReferenceNecessaryTypeInfo(typeof(global::Xunit.TheoryDataRow<,,,,,,,>));
            ReferenceNecessaryTypeInfo(typeof(global::Xunit.TheoryDataRow<,,,,,,,,>));
            ReferenceNecessaryTypeInfo(typeof(global::Xunit.TheoryDataRow<,,,,,,,,,>));
            ReferenceNecessaryTypeInfo(typeof(global::Xunit.TheoryDataRow<,,,,,,,,,,>));
            ReferenceNecessaryTypeInfo(typeof(global::Xunit.TheoryDataRow<,,,,,,,,,,,>));
            ReferenceNecessaryTypeInfo(typeof(global::Xunit.TheoryDataRow<,,,,,,,,,,,,>));
            ReferenceNecessaryTypeInfo(typeof(global::Xunit.TheoryDataRow<,,,,,,,,,,,,,>));
            ReferenceNecessaryTypeInfo(typeof(global::Xunit.TheoryDataRow<,,,,,,,,,,,,,,>));
            // Now reference the System.ValueTuple types, as they are used in the generated code for TheoryData with multiple generic parameters.
            ReferenceNecessaryTypeInfo(typeof(global::System.ValueTuple));
            ReferenceNecessaryTypeInfo(typeof(global::System.ValueTuple<>));
            ReferenceNecessaryTypeInfo(typeof(global::System.ValueTuple<,>));
            ReferenceNecessaryTypeInfo(typeof(global::System.ValueTuple<,,>));
            ReferenceNecessaryTypeInfo(typeof(global::System.ValueTuple<,,,>));
            ReferenceNecessaryTypeInfo(typeof(global::System.ValueTuple<,,,,>));
            ReferenceNecessaryTypeInfo(typeof(global::System.ValueTuple<,,,,,>));
            ReferenceNecessaryTypeInfo(typeof(global::System.ValueTuple<,,,,,,>));
            ReferenceNecessaryTypeInfo(typeof(global::System.ValueTuple<,,,,,,,>));
        }
        private static void ReferenceNecessaryTypeInfo([global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All)] Type _)
        {
            // No implementation needed, the method parameter attribute is used to preserve the type information of the specified type for AOT compilation.
        }
    }
}
