// <auto-generated />
using System.Linq;

namespace Scand.StormPetrel.Generator.TargetProject
{
    // {GeneratedCodeAttribute}
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class GeneratorRewriter : global::Scand.StormPetrel.Generator.Abstraction.IGeneratorRewriter
    {
        public readonly global::Scand.StormPetrel.Generator.Abstraction.IGeneratorBackuper _backuper = (global::Scand.StormPetrel.Generator.Abstraction.IGeneratorBackuper)null;
        private static global::System.Collections.Concurrent.ConcurrentDictionary<string, object> filePathToLock = new global::System.Collections.Concurrent.ConcurrentDictionary<string, object>();

        public global::Scand.StormPetrel.Generator.Abstraction.RewriteResult Rewrite(global::Scand.StormPetrel.Generator.Abstraction.GenerationRewriteContext generationRewriteContext)
        {
            var generationContext = generationRewriteContext.GenerationContext;
            var filePath = generationContext.MethodSharedContext.FilePath;
            global::Scand.StormPetrel.Rewriter.CSharp.SyntaxRewriter.AbstractRewriter rewriter = null;
            var extraContext = generationContext.ExtraContext;
            if (extraContext is global::Scand.StormPetrel.Generator.Abstraction.ExtraContext.InitializerContext initializerContext)
            {
                switch (initializerContext.Kind)
                {
                    case global::Scand.StormPetrel.Generator.Abstraction.ExtraContext.InitializerContextKind.VariableDeclaration:
                        rewriter = new global::Scand.StormPetrel.Rewriter.CSharp.SyntaxRewriter.DeclarationRewriter(generationContext.ExpectedVariablePath, generationRewriteContext.Value, initializerContext.InvocationPath);
                        break;
                    case global::Scand.StormPetrel.Generator.Abstraction.ExtraContext.InitializerContextKind.VariableAssignment:
                        rewriter = new global::Scand.StormPetrel.Rewriter.CSharp.SyntaxRewriter.AssignmentRewriter(generationContext.ExpectedVariablePath, generationRewriteContext.Value, initializerContext.InvocationPath);
                        break;
                    default:
                        throw new global::System.InvalidOperationException("Unexpected Kind = " + initializerContext.Kind);
                }
            }
            else if (extraContext is global::Scand.StormPetrel.Generator.Abstraction.ExtraContext.AttributeContext attributeContext)
            {
                rewriter = new global::Scand.StormPetrel.Rewriter.CSharp.SyntaxRewriter.AttributeRewriter(generationContext.ExpectedVariablePath, attributeContext.Name, attributeContext.Index, attributeContext.ParameterIndex, generationRewriteContext.Value);
            }
            else if (extraContext is global::Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.InvocationSourceContext invocationSourceContext)
            {
                var methodInfo = invocationSourceContext.MethodInfo;
                if (methodInfo != null)
                {
                    string[] methodPath = invocationSourceContext.Path;
                    if (methodInfo is global::Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodBodyStatementInfo methodBodyStatementInfo)
                    {
                        rewriter = new global::Scand.StormPetrel.Rewriter.CSharp.SyntaxRewriter.BodyStatementRewriter(methodPath, generationRewriteContext.Value, methodBodyStatementInfo.StatementIndex, methodBodyStatementInfo.StatementNodeKind, methodBodyStatementInfo.StatementNodeIndex);
                    }
                    else if (methodInfo is global::Scand.StormPetrel.Generator.Abstraction.ExtraContext.InvocationSource.MethodNodeInfo methodNodeInfo)
                    {
                        var staticMethodInfo = GetStaticMethodInfo(methodPath, methodNodeInfo.MethodArgsCount);
                        methodPath = staticMethodInfo.MethodPath;
                        filePath = staticMethodInfo.FilePath;
                        rewriter = new global::Scand.StormPetrel.Rewriter.CSharp.SyntaxRewriter.ExpressionRewriter(methodPath, methodNodeInfo.NodeKind, methodNodeInfo.NodeIndex, generationRewriteContext.Value, global::System.Array.Empty<string>());
                    }
                    else
                    {
                        throw new global::System.InvalidOperationException("Unexpected MethodInfo type: " + methodInfo.GetType().FullName);
                    }
                }
                else
                {
                    var staticPropertyInfo = GetStaticPropertyInfo(invocationSourceContext.Path, true);
                    filePath = staticPropertyInfo.FilePath;
                    rewriter = new global::Scand.StormPetrel.Rewriter.CSharp.SyntaxRewriter.DeclarationRewriter(staticPropertyInfo.PropertyPath, generationRewriteContext.Value, global::System.Array.Empty<string>());
                }
            }
            else if (extraContext is global::Scand.StormPetrel.Generator.Abstraction.ExtraContext.TestCaseSourceContext testCaseSourceContext)
            {
                var testCaseSourceContextPath = testCaseSourceContext.Path;
                var parameterDefaultValues =
                    generationContext
                        .MethodSharedContext
                        .Parameters
                        .Select(x => GetCompatibleDefaultExpression(x.TypeToken, x.DefaultExpression))
                        .ToArray();
                var testCaseSourcePropertyInfo = GetStaticPropertyInfo(testCaseSourceContextPath, false);
                string[] testCaseSourcePath = null;
                if (testCaseSourcePropertyInfo == null)
                {
                    var testCaseSourceMethodInfo = GetStaticMethodInfo(testCaseSourceContextPath, -1);
                    testCaseSourcePath = testCaseSourceMethodInfo.MethodPath;
                    filePath = testCaseSourceMethodInfo.FilePath;
                }
                else
                {
                    testCaseSourcePath = testCaseSourcePropertyInfo.PropertyPath;
                    filePath = testCaseSourcePropertyInfo.FilePath;
                }
                rewriter = new global::Scand.StormPetrel.Rewriter.CSharp.SyntaxRewriter.EnumerableResultRewriter(testCaseSourcePath, testCaseSourceContext.RowIndex, testCaseSourceContext.ColumnIndex, generationRewriteContext.Value, parameterDefaultValues, testCaseSourceContext.InvocationPath);
            }
            else
            {
                throw new global::System.InvalidOperationException();
            }

            string backupFilePath = null;
            if (_backuper != null)
            {
                backupFilePath = _backuper.Backup(new global::Scand.StormPetrel.Generator.Abstraction.GenerationBackupContext()
                {
                    GenerationContext = generationContext,
                    FilePath = filePath,
                });
            }

            var fileLock = filePathToLock.GetOrAdd(filePath, _ => new object());
            bool isRewritten;
            lock (fileLock)
            {
                isRewritten = global::Scand.StormPetrel.Rewriter.Extension.CSharpSyntaxRewriterExtension.Rewrite(rewriter, filePath);
            }

            return new global::Scand.StormPetrel.Generator.Abstraction.RewriteResult { IsRewritten = isRewritten, BackupFilePath = backupFilePath };
        }

        private static global::Scand.StormPetrel.Generator.TargetProject.GeneratorRewriter.StaticPropertyInfo GetStaticPropertyInfo(string[] staticPropertyPath, bool throwIfNotFound)
        {
            staticPropertyPath = staticPropertyPath.ToArray(); //make a copy for later normalization
            staticPropertyPath[staticPropertyPath.Length - 1] = staticPropertyPath[staticPropertyPath.Length - 1]
                                                                    .Replace("[*]", "");
            var match = _staticPropertyInfoArray
                                .Where(x => x.PropertyPath.SequenceEqual(staticPropertyPath))
                                .FirstOrDefault();
            if (match == null)
            {
                // False positive match is possible. However, we prefer it against semantic analysis.
                match = _staticPropertyInfoArray
                                .OrderByDescending(x => x.PropertyPath.Length)
                                .Where(x => ParentPathHasChild(x.PropertyPath, staticPropertyPath))
                                .FirstOrDefault();
                if (match == null)
                {
                    match = _staticPropertyInfoArray
                                    .OrderBy(x => x.PropertyPath.Length)
                                    .Where(x => ParentPathHasChild(staticPropertyPath, x.PropertyPath))
                                    .FirstOrDefault();
                }
            }
            if (throwIfNotFound && match == null)
            {
                string path = string.Join(".", staticPropertyPath);
                throw new global::System.InvalidOperationException($"Cannot find static property file path for {path}");
            }
            return match;
        }

        private static global::Scand.StormPetrel.Generator.TargetProject.GeneratorRewriter.StaticMethodInfo GetStaticMethodInfo(string[] staticMethodPath, int methodArgsCount)
        {
            var match = _staticMethodInfoArray
                                .Where(x => x.MethodPath.SequenceEqual(staticMethodPath) && (methodArgsCount < 0 || x.MethodArgsCount == methodArgsCount))
                                .FirstOrDefault();
            if (match == null)
            {
                var argsAsMethodInfo = new global::Scand.StormPetrel.Generator.TargetProject.GeneratorRewriter.StaticMethodInfo
                {
                    MethodPath = staticMethodPath,
                    MethodArgsCount = methodArgsCount,
                };
                // False positive match is possible. However, we prefer it against semantic analysis.
                match = _staticMethodInfoArray
                                .OrderByDescending(x => x.MethodPath.Length)
                                .Where(x => ParentMethodHasChild(x, argsAsMethodInfo))
                                .FirstOrDefault();
                if (match == null)
                {
                    match = _staticMethodInfoArray
                                .OrderBy(x => x.MethodPath.Length)
                                .Where(x => ParentMethodHasChild(argsAsMethodInfo, x))
                                .FirstOrDefault();
                }
            }
            if (match == null)
            {
                string path = string.Join(".", staticMethodPath);
                throw new global::System.InvalidOperationException($"Cannot find static method file path for {path}");
            }
            return match;
        }

        private static bool ParentMethodHasChild(StaticMethodInfo parent, StaticMethodInfo child) =>
            parent.MethodPath.Length >= child.MethodPath.Length
                ? (parent.MethodArgsCount < 0 || child.MethodArgsCount < 0 || parent.MethodArgsCount == child.MethodArgsCount)
                    && parent.MethodPath.Skip(parent.MethodPath.Length - child.MethodPath.Length).SequenceEqual(child.MethodPath)
                : false;

        private static bool ParentPathHasChild(string[] parent, string[] child) =>
            parent.Length >= child.Length
                ? parent.Skip(parent.Length - child.Length).SequenceEqual(child)
                : false;

        private static string GetCompatibleDefaultExpression(string typeToken, string defaultValue) =>
            defaultValue == null || defaultValue == "default"
                ? $"default({typeToken})"
                : defaultValue;
    }
}
