// <auto-generated />
namespace Scand.StormPetrel.Generator.TargetProject
{
    // {GeneratedCodeAttribute}
    public sealed class GeneratorBackuper : global::Scand.StormPetrel.Generator.Abstraction.IGeneratorBackuper
    {
        private static global::System.Collections.Concurrent.ConcurrentDictionary<string, object> FilePathToLockObject = new global::System.Collections.Concurrent.ConcurrentDictionary<string, object>();
        private static global::System.Collections.Concurrent.ConcurrentDictionary<string, string> FilePathToBackupFilePath = new global::System.Collections.Concurrent.ConcurrentDictionary<string, string>();

        /// <summary>
        /// Creates backup file based on <paramref name="generationBackupContext"/>.
        /// </summary>
        /// <param name="generationBackupContext"></param>
        /// <returns></returns>
        public string Backup(global::Scand.StormPetrel.Generator.Abstraction.GenerationBackupContext generationBackupContext)
        {
            var contextFilePath = generationBackupContext.FilePath;
            lock (FilePathToLockObject.GetOrAdd(contextFilePath, new object()))
            {
                if (!FilePathToBackupFilePath.TryGetValue(contextFilePath, out var backupFilePath))
                {
                    var currentDateTimeForFileExt = global::System.DateTime.Now.ToString("yyyyMMddHHmmssfffffff");
                    backupFilePath = $"{contextFilePath}.backup{currentDateTimeForFileExt}";
                    global::System.IO.File.Copy(contextFilePath, backupFilePath);
                    if (!FilePathToBackupFilePath.TryAdd(contextFilePath, backupFilePath))
                    {
                        throw new global::System.InvalidOperationException("This code line is unreachable due to locking mechanism above");
                    }
                }
                return backupFilePath;
            }
        }
    }
}
